LST-1 Complete README.md
crococoders/lostie pull request #49
Opened 2023-01-12 03:32 UTC by alimsanzhar

Closes https://github.com/crococoders/lostie/issues/1

2023-01-13 12:21 UTC, oizuldan requested changes

2023-01-13 12:21 UTC, oizuldan commented on README.md
> +- Javascript, Typescript, NodeJS.
```suggestion
- Javascript, Typescript, NodeJS, Grammy
```

2023-01-13 12:21 UTC, oizuldan commented on README.md
> +- PostgreSQL
```suggestion
- PostgreSQL, Sequelize ORM
```

2023-01-13 12:21 UTC, oizuldan commented on README.md
> +- The event storming details are located in [Miro board](https://miro.com/app/board/uXjVP99l3a8=/?share_link_id=985749745364).
```suggestion
- The event storming details are located in [Miro board](https://miro.com/app/board/uXjVP99l3a8=/?share_link_id=985749745364) (a bit outdated, will be replaced soon). 
```

2023-01-13 12:21 UTC, oizuldan commented on README.md
> +Lostie is a lost and found client-server application with Domain-Driven Design approach used for documents search.
```suggestion
`Lostie` - document search aggregator for those who lost or found any personal document. The main idea is to help people with the search for the documents that they have lost. Currently, we support the following document types: Passport, National ID, Driver License, Bank Card. Please create issue if you have any suggestion for new document type.
```

2023-01-13 12:21 UTC, oizuldan commented on README.md
> +## Tech stack
```suggestion
## Tech stack
We decided to implement this project using Monorepo and DDD approach. Here is the tech stack:
- root -> Lerna, Yarn Workspaces, Docker
    - backend ->  NodeJS, PostgreSQL, Sequelize ORM, Typescript
    - telegram-bot -> Grammy, Typescript
```

2023-01-16 13:59 UTC, nurbekismagulov approved these changes

2023-01-16 14:03 UTC, merged